### ISSUE TITLE
hyundai golvis page

### ISSUE THREAD

**Issue by ayazvayani** [radean/smc#10]
Cover picture change with Hyundai Golvis Ship

rest all images remove
remove transporation & logistic part from this page we place it as separate page.

text use as ABSA heading & para style as discussed

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
sharp image of cover picture
Remove about heading line

**Comment by ayazvayani** [comment]
Email sent on: Sep 19, 2018, 11:13 AM
subject: | Fwd: FW: SMC Web Site- update

ADD with formatting like heading and paragraph.

Finished Vehicle shipping
Major services
·         Operate about 60 PCC (Pure Car Carrier) and PCTC (Pure Car and Truck Carrier).
·         Service quality management using global systems and global networks

Service route and ship status
·         Hyundai Glovis has over 60 vessels of various sizes to optimize the operation of all service routes.

**Comment by radean** [comment]
Done
