### ISSUE TITLE
pemra Page

### ISSUE THREAD

**Issue by ayazvayani** [radean/smc#11]
Cover picture will be perma shipping image

rest all images remove
remove explore other services from all for pages

text use as ABSA heading & para style as discussed

**Comment by radean** [comment]
done

**Comment by ayazvayani** [comment]
sharp image of cover picture
unbold 1st line continue as paragraph 2nd line
remove space
remove about perma shipping
remove box but content should there as continue paragraph, remove we are contantly line.
logo should be on top where it looks fine.
