### ISSUE TITLE
service page

### ISSUE THREAD

**Issue by ayazvayani** [radean/smc#12]
remove cover picture they are strong competitor of them

put absa services page picture on it

**Comment by radean** [comment]
cannot Understand Issue

**Comment by ayazvayani** [comment]
coover images text services remove.

**Comment by radean** [comment]
Removed Already

**Comment by ayazvayani** [comment]
remove 4 boxes ocean, air, land and ware housing
Change image of transportation box there are to many mountains as discussed.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Email sent on: Sep 19, 2018, 11:13 AM
subject: | Fwd: FW: SMC Web Site- update


SERVICES (TRANSPORTATION)
Replace paragraph and table
