### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by ayazvayani** [radean/smc#7]
Main page cover picture of truck will be replace with collage of three picture which is place in VDM/WEB/SMC
----------------
**following use as footer** 
SMC logo call centre & timing row
get in touch row
------------------
also remove social icons complete row

**Comment by radean** [comment]
Collage is not looking great at all

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
cover images will be collection of all pages cover picture with bullet slider.
4 tabs land, air, ocean and ware house will be removed.
when we open web at least some text wil be shown in first view as discussed
cover photo text font will same as ABSACO cover text fonts
remove extra line spacing
about us blue line little bit increase.

**Comment by radean** [comment]
done
