### ISSUE TITLE
Eukor Golvis Page

### ISSUE THREAD

**Issue by ayazvayani** [radean/smc#9]
Cover picture change with Eukor Golvis Ship

rest all images remove

text use as ABSA heading & para style as discussed

**Comment by radean** [comment]
Done.

**Comment by ayazvayani** [comment]
sharp image of cover picture
remove about heading
remove space
remove box but content should there as continue paragraph, Worldwide heading both words same formating bold with reduce font size applies same on all heading or this page. as discussed..
logo should be on top where it looks fine.
extra line spacing will remove.
